package net.jforum.dao.generic;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Timestamp;

import net.jforum.dao.CommentDAO;
import net.jforum.entities.Comment;
import net.jforum.exceptions.DatabaseException;
import net.jforum.util.DbUtils;
import net.jforum.util.preferences.SystemGlobals;

public class GenericCommentDAO extends AutoKeys implements CommentDAO {

	public int addNew(Comment comment) {
		// TODO Auto-generated method stub
		try {
			this.addNewComment(comment);
			
			return comment.getId();
		}
		catch (Exception e) {
			throw new DatabaseException(e);
		}
	}

	protected void addNewComment(Comment comment)
	{
		PreparedStatement pstmt = null;
		try {
			pstmt = this.getStatementForAutoKeys("CommentModel.addNewComment");
			
			pstmt.setInt(1, comment.getPostId());
			pstmt.setInt(2, comment.getTopicId());
			pstmt.setLong(3, comment.getUserId());
			pstmt.setString(4, comment.getText());
			pstmt.setTimestamp(5, new Timestamp(comment.getTime().getTime()));
			
			this.setAutoGeneratedKeysQuery(SystemGlobals.getSql("CommentModel.lastGeneratedPostId"));
			int commentId = this.executeAutoKeysQuery(pstmt);
			comment.setId(commentId);
		}
		catch (SQLException e) {
			throw new DatabaseException(e);
		}
		finally {
			DbUtils.close(pstmt);
		}
	}
}
